Furniture = { 
    ['Categories'] = {
        {'table', 'Mesas'},
        {'chair', 'Sillas'},
        {'decorations', 'Decoraciones'},
        {'electronics', 'Electronicos'},
        {'Plants', 'Plantas'},
        {'sofa', 'Sofas'},
        {'bed', 'Camas'},
        {'CashGoldJewels', 'Joyas'},
        {'Drugs', 'Drogas'},
        {'FoodandDrinks','Comida y Bebida'},
        {'lights', 'Luces'},
        {'kitchen', 'Cocina'},
        {'accessory', 'Otros'},
        {'Storage', 'Almacenamiento'}
    },

    ['chair'] = {
        {'Silla de mesa', 'prop_table_02_chr', 50},
        {'Sillón', 'prop_cs_folding_chair_01', 150},
        {'Silla roca', 'prop_rock_chair_01', 150},
        {'Silla de ruedas', 'prop_wheelchair_01', 150},
        {'Silla de oficina', 'p_clb_officechair_s', 125},
        {'Silla de oficina 2', 'prop_off_chair_04_s', 150},
        {'Silla de oficina 3', 'prop_cs_office_chair', 150},
        {'Silla de oficinar 4', 'prop_off_chair_04', 150},
        {'Silla de oficina 5', 'prop_off_chair_03', 150},
        {'Silla de oficina 6', 'prop_off_chair_01', 150},
        {'Silla de oficina 7', 'prop_off_chair_05', 150},
        {'Silla de oficina 8', 'v_club_officechair', 150},
        {'Silla de oficina 9', 'v_corp_offchair', 150},
        {'Silla de tortura', 'prop_torture_ch_01', 150},
        {'Silla de comedor', 'p_dinechair_01_s', 150},
        {'Silla de comedor 2', 'p_dinechair_01_s', 150},
        {'Silla sol', 'p_soloffchair_s', 150},
        {'Silla sol 2', 'p_soloffchair_s', 150},
        {'Silla de yate', 'prop_sol_chair', 150},
        {'Silla 2', 'prop_chair_02', 150},
        {'Silla 3', 'prop_chair_01b', 150},
        {'Silla 4', 'prop_chair_04a', 150},
        {'Silla 5', 'prop_chair_04b', 150},
        {'Silla 6', 'prop_chair_06', 150},
        {'Silla 7', 'prop_chair_07', 150},
        {'Silla 8', 'prop_chair_09', 150},
        {'Silla 9', 'prop_chateau_chair_01', 150},
        {'Silla 10', 'prop_clown_chair', 150},
        {'Silla 11', 'prop_direct_chair_01', 150},
        {'Silla 12', 'prop_cs_office_chair', 150},
        {'Silla 13', 'prop_gc_chair02', 150},
        {'Silla 14', 'prop_ld_farm_chair01', 150},
        {'Silla 15', 'v_ilev_chair02_ped', 150},
        {'Silla 16', 'v_corp_cd_chair', 150},
        {'Silla 17', 'v_corp_bk_chair3', 150},
        {'Silla 18', 'prop_skid_chair_03', 150},
        {'Silla 19', 'prop_table_01_chr_a', 150},
        {'Silla 20', 'prop_table_01_chr_b', 150},
        {'Silla 21', 'prop_table_02_chr', 150},
        {'Silla 22', 'prop_table_03_chr', 150},
        {'Silla 23', 'prop_table_03b_chr', 150},
        {'Silla 24', 'prop_table_04_chr', 150},
        {'Silla 25', 'prop_table_05_chr', 150},
    },
    ['decorations'] = {
        {'Botella', 'apa_mp_h_acc_bottle_01', 100},
        {'Velas', 'apa_mp_h_acc_candles_01', 100},
        {'Espejo', 'p_int_jewel_mirror', 100},
        {'Lámina', 'apa_mp_h_acc_dec_plate_01', 100},
        {'Jarrón', 'apa_mp_h_acc_vase_01', 100},
        {'Jarrón 2', 'v_res_desktidy', 100},
        {'Flores', 'apa_mp_h_acc_vase_flowers_01', 100},
        {'Cenicero', 'ex_prop_ashtray_luxe_02', 100},
        {'Diario', 'p_cs_newspaper_s', 100},
        {'Folleto', 'p_cs_pamphlet_01_s', 100},
        {'Bong', 'prop_bong_01', 100},
        {'Frambuesa', 'prop_mr_rasberryclean', 100},
        {'Guitarra', 'prop_acc_guitar_01', 100},
        {'Tablero', 'p_planning_board_04', 100},
        {'Reloj 1', 'prop_hotel_clock_01', 100},
        {'Reloj 2', 'prop_big_clock_01', 100},
        {'Reloj 3', 'prop_egg_clock_01', 100},
        {'Cuadro', 'v_ilev_ra_doorsafe', 100},
        {'Dardo', 'prop_dart_bd_cab_01', 100},
        {'Dardo 2', 'prop_dart_bd_01', 100},
        {'Bicicleta de ejercicio', 'prop_exercisebike', 300},            
        {'Laz', 'p_laz_j02_s', 300}
    },
    ['table'] = {
        {'Mesa TV', 'prop_tv_cabinet_03', 500, true},
        {'Mesa de granja', 'prop_ld_farm_table02', 300},
        {'Mesa de granja 2', 'prop_ld_farm_table01', 300},
        {'Mesa café', 'prop_fbi3_coffee_table', 300},
        {'Mesa café 2', 'prop_t_coffe_table', 300},
        {'Mesa café 2', 'prop_t_coffe_table_02', 300},
        {'Mesa triple', 'prop_tri_table_01', 300},
        {'Mesa de protesta', 'prop_protest_table_01', 300},
        {'Mesa 2', 'hei_prop_yah_table_01', 150},
        {'Mesa 3', 'hei_prop_yah_table_02', 150},
        {'Mesa 4', 'hei_prop_yah_table_03', 150},
        {'Mesa 5', 'prop_ld_farm_table01', 150},
        {'Mesa 6', 'prop_ld_farm_table02', 150},
        {'Mesa 7', 'prop_chateau_table_01', 150},
        {'Mesa 8', 'prop_fbi3_coffee_table', 150},
        {'Mesa 9', 'prop_patio_lounger1_table', 150},
        {'Mesa 10', 'prop_picnictable_01', 150},
        {'Mesa 11', 'prop_proxy_chateau_table', 150},
        {'Mesa 12', 'prop_rub_table_01', 150},
        {'Mesa 13', 'prop_rub_table_02', 150},
        {'Mesa 14', 'prop_table_01', 150},
        {'Mesa 15', 'prop_table_02', 150},
        {'Mesa 16', 'prop_table_03', 150},
        {'Mesa 17', 'prop_table_03b', 150},
        {'Mesa 18', 'prop_table_04', 150},
        {'Mesa 19', 'prop_table_05', 150},
        {'Mesa 20', 'prop_table_06', 150},
        {'Mesa 21', 'prop_table_07', 150},
        {'Mesa 22', 'prop_table_08', 150},
        {'Mesa 23', 'prop_table_08_chr', 150},
        {'Mesa 24', 'prop_ven_market_table1', 150},
        {'Mesa 25', 'v_ilev_liconftable_sml', 150},
        {'Mesa 26', 'prop_table_tennis', 150},
        {'Mesa 27', 'prop_pooltable_02', 150},
        {'Mesa 28', 'prop_astro_table_02', 150},
        {'Mesa 29', 'prop_astro_table_01', 150}
    },
    ['electronics'] = {
        {'TV plana', 'prop_tv_flat_02', 750},
        {'TV gorda', 'prop_tv_06', 350},
        {'TV pequeño y gordo', 'prop_tv_02', 250},
        {'Radio', 'prop_portable_hifi_01', 100},
        {'Computadora nueva', 'prop_dyn_pc_02', 500},
        {'Computadora vieja', 'prop_pc_01a', 100},
        {'Monitor', 'prop_monitor_01c', 75},
        {'Monitor 2', 'prop_ld_monitor_01', 75},
        {'Monitor 3', 'prop_monitor_03b', 25},
        {'Celular', 'p_amb_phone_01', 75},
        {'Celular viejo', 'prop_v_m_phone_o1s', 75},
        {'Celular de oficina', 'prop_office_phone_tnt', 75},
        {'Celular CS', 'prop_cs_phone_01', 75},
        {'Tablet 1', 'prop_cs_tablet_02', 75},
        -- {'Tablet 2', 'prop_cs_tablet_01', 75},
        {'Table mic', 'prop_table_mic_01', 75},
        {'Radio', 'prop_portable_hifi_01', 75},
        {'Laptop', 'p_amb_lap_top_02', 75},
        {'Laptop 2', 'p_cs_laptop_02', 75},
        {'Laptop Cerrada', 'p_cs_laptop_02_w', 75},
        {'Teclado', 'prop_ld_keypad_01b', 75},
        {'Teclado 2', 'prop_ld_keypad_01', 75},
        {'PC', 'prop_dyn_pc', 75},
        {'PC 2', 'prop_dyn_pc_02', 75},
        {'PC 3', 'prop_pc_01a', 75},
        {'PC 4', 'hei_prop_heist_pc_01', 75},
        {'PC 5', 'prop_pc_02a', 75},
        {'Mouse', 'prop_cs_mouse_01', 75},
        {'Mouse 2', 'prop_mouse_01a', 75},
        {'Alfombrilla de ratón', 'v_res_mousemat', 75},
        {'Teclado', 'hei_prop_hei_cs_keyboard', 75},
        {'Teclado 2', 'prop_cs_keyboard_01', 75},
        {'Teclado 3', 'prop_keyboard_01a', 75}
    },
    ['bed'] = {
        {'Cama', 'v_res_msonbed_s', 450}, 
        {'Cama 2', 'p_lestersbed_s', 150},
        {'Cama 3', 'p_mbbed_s', 150},
        {'Cama 4', 'p_v_res_tt_bed_s', 150},
        {'Cama 5', 'v_res_msonbed_s', 150}
    },
    ['sofa'] = {
        {'Cojín de sofá', 'v_ilev_m_sofacushion', 150},
        {'Sofa de cuero', 'p_v_med_p_sofa_s', 300},
        {'Sofá usado', 'v_tre_sofa_mess_c_s', 150},
        {'Sofá de tela', 'p_res_sofa_l_s', 225},
        {'Sofá', 'miss_rub_couch_01', 225},
        {'Sofa 1', 'prop_t_sofa_02', 300},
        {'Sofa 2', 'prop_t_sofa', 300},
        {'Sofa 3', 'p_lev_sofa_s', 150},
        {'Sofa 4', 'p_res_sofa_l_s', 150},
        {'Sofa 5', 'p_v_med_p_sofa_s', 150},
        {'Sofa 6', 'p_yacht_sofa_01_s', 150},
        {'Sofa 7', 'v_ilev_m_sofa', 150},
        {'Sofa 8', 'v_res_tre_sofa_s', 150},
        {'Sofa 9', 'prop_rub_couch02', 150},
        {'Sofa 13', 'v_tre_sofa_mess_a_s', 150},
        {'Sofa 14', 'v_tre_sofa_mess_b_s', 150},
        {'Sofa 15', 'v_tre_sofa_mess_c_s', 150},
        {'Sofa 16', 'prop_ld_farm_chair01', 150},
        {'Sofa 17', 'prop_ld_farm_couch01', 150},
        {'Sofa 18', 'prop_ld_farm_couch02', 150}
    },
    ['Plants'] = {
        {'Planta 1', 'p_int_jewel_plant_02', 100},
        {'Planta 2', 'p_int_jewel_plant_01', 100},
        {'Planta 3', 'prop_fbibombplant', 100},
        {'Planta 4', 'prop_fib_plant_01', 100},
        {'Planta 5', 'prop_fib_plant_02', 100},
        {'Planta 6', 'prop_ld_dstplanter_01', 100},
        {'Planta 7', 'prop_ld_planter2b', 100},
        {'Planta 8', 'prop_plant_int_01a', 100},
        {'Planta 9', 'prop_plant_int_01b', 100},
        {'Planta 10', 'prop_plant_int_02a', 100},
        {'Planta 11', 'prop_plant_int_02b', 100},
        {'Planta 12', 'prop_plant_int_03a', 100},
        {'Planta 13', 'prop_plant_int_03c', 100},
        {'Planta 14', 'prop_plant_int_03b', 100},
        {'Planta 15', 'prop_plant_int_04b', 100},
        {'Planta 16', 'prop_plant_int_04a', 100},
        {'Planta 17', 'prop_plant_int_04c', 100},
        {'Planta 13', 'prop_plant_palm_01a', 100},
        {'Planta 14', 'prop_plant_palm_01c', 100},
        {'Planta 15', 'prop_pot_plant_01b', 100},
        {'Planta 16', 'prop_pot_plant_01a', 100},
        {'Planta 17', 'prop_pot_plant_01c', 100},
        {'Planta 18', 'prop_pot_plant_01d', 100},
        {'Planta 19', 'prop_pot_plant_03c', 100},
        {'Planta 20', 'prop_pot_plant_05a', 100}
    },
    ['CashGoldJewels'] = {
        {'Caja de efectivo', 'prop_cash_case_02', 50},
        {'Caja de efectivo', 'prop_cash_crate_01', 50},
        {'Caja de efectivo 2', 'hei_prop_cash_crate_half_full', 50},
        {'Nota en efectivo', 'prop_anim_cash_note_b', 50},
        {'Pila de dinero', 'prop_anim_cash_pile_01', 50},
        {'Carrito de efectivo', 'prop_cash_trolly', 50},
        {'Carrito de efectivo 2', 'prop_poly_bag_money', 50},
        {'Carretilla de oro llena', 'prop_gold_trolly_full', 50},
        {'Carrito de oro', 'prop_gold_trolly', 50},
        {'Barra de oro', 'prop_gold_bar', 50},
        {'Oro grande', 'prop_large_gold', 50},
        {'Oro grande 2', 'p_large_gold_s', 50},
        {'Cofre de oro', 'prop_ld_gold_chest', 50},
        {'Pequeño oro', 'prop_peyote_gold_01', 50},
        {'Joya 1', 'prop_jewel_03b', 50},
        {'Joya 2', 'prop_jewel_04b', 50},
        {'Joya 3', 'prop_jewel_02b', 50},
        {'Joya 4', 'prop_jewel_pickup_new_01', 50},
        {'Joya 5', 'prop_jewel_04b', 50},
        {'Joya 6', 'prop_cs_beer_box', 50}
    },
    ['Drugs'] = {
        {'Droga 1', 'prop_weed_pallet', 500},
        {'Droga 2', 'hei_prop_hei_drug_pack_01b', 100},
        {'Droga 3', 'hei_prop_hei_drug_pack_01a', 100},
        {'Droga 4', 'hei_prop_hei_drug_pack_02', 100},
        {'Droga 5', 'hei_prop_heist_drug_tub_01', 100},
        {'Droga 6', 'ng_proc_drug01a002', 100},
        {'Droga 7', 'prop_drug_bottle', 100},
        {'Droga 8', 'hei_prop_hei_drug_case', 100},
        {'Droga 9', 'prop_drug_burner', 100},
        {'Droga 10', 'prop_drug_erlenmeyer', 100},
        {'Droga 11', 'prop_drug_package', 100},
        {'Droga 12', 'prop_drug_package_02', 100},
        {'Droga 13', 'prop_mp_drug_package', 100},
        {'Droga 14', 'prop_mp_drug_pack_blue', 100},
        {'Droga 15', 'prop_mp_drug_pack_red', 100},
        {'Droga 16', 'prop_coke_block_01', 100},
        {'Droga 17', 'prop_coke_block_half_a', 100},
        {'Droga 18', 'p_meth_bag_01_s', 500},
        {'Droga 19', 'prop_meth_bag_01', 100},
        {'Droga 20', 'prop_meth_setup_01', 100}
    },
    ['FoodandDrinks'] = {
        {'Cuenco de maní', 'prop_peanut_bowl_01', 50},
        {'cuenco', 'prop_cs_bowl_01', 50},
        {'Copa BS', 'prop_cs_bs_cup', 50},
        {'Café', 'p_ing_coffeecup_02', 50},
        {'Puesto de frutas 1', 'prop_fruit_stand_03', 50},
        {'Puesto de frutas 2', 'prop_fruit_stand_02', 50},
        {'Puesto de frutas 3', 'prop_fruit_stand_01', 50},
        {'Puesto de frutas 4', 'prop_fruit_stand_03', 50},
        {'Puesto de frutas 5', 'prop_fruit_stand_03', 50},
        {'Caja de cerveza', 'prop_cs_beer_box', 50},
        {'Cerveza 2', 'beerrow_world', 50},
        {'Cerveza 3', 'prop_amb_beer_bottle', 50},
        {'Cerveza 4', 'prop_beer_blr', 50},
        {'Cerveza 5', 'prop_beer_logger', 50},
        {'Comida', 'ng_proc_food_bag01a', 50},
        {'Comida 2', 'prop_food_bs_burg1', 50},
        {'Comida 3', 'prop_food_bs_burg3', 50},
        {'Comida 4', 'prop_food_bs_chips', 50},
        {'Comida 5', 'prop_food_bs_burger2', 50},
        {'Comida 6', 'prop_food_bs_coffee', 50},
        {'Comida 7', 'prop_food_cups1', 50},
        {'Comida 8', 'prop_food_cb_cups01', 50},
        {'Comida 9', 'prop_food_cb_cups02', 50},
        {'Comida 10', 'prop_food_bs_cups02', 50}
    },
    ['lights'] = {
        {'Luz ', 'prop_cd_lamp', 150},
        {'Luz 2', 'v_ret_fh_walllighton', 150},
        {'Luz 3', 'v_ret_gc_lamp', 150},
        {'Luz 4', 'hei_prop_hei_bnk_lamp_02', 150},
        {'Luz 5', 'prop_ld_cont_light_01', 150},
        {'Luz 6', 'hei_prop_hei_bnk_lamp_01', 150},
        {'Luz 7', 'prop_chall_lamp_02', 150},
        {'Luz 8', 'v_ilev_fh_lampa_on', 150},
        {'Luz 9', 'prop_construcionlamp_01', 150},
        {'Luz 10', 'hei_prop_bank_ornatelamp', 150},
        {'Luz 11', 'prop_kino_light_03', 150},
        {'Luz 12', 'prop_oldlight_01c', 150},
        {'Luz 13', 'prop_recycle_light', 150},
        {'Luz 14', 'prop_studio_light_01', 150},
        {'Luz 15', 'prop_studio_light_02', 150},
        {'Luz 16', 'hei_prop_bank_ornatelamp', 150},
        {'Luz 17', 'prop_wall_light_02a', 150},
        {'Luz 18', 'prop_wall_light_03a', 150},
        {'Luz 19', 'prop_wall_light_04a', 150},
        {'Luz 20', 'prop_wall_light_05a', 150},
        {'Luz 21', 'prop_wall_light_05c', 150}

      },
    
      ['kitchen'] = {
        {'Maquina de cafe', 'apa_mp_h_acc_coffeemachine_01', 150},
        {'Escala', 'bkr_prop_coke_scale_01', 150},
        {'Compartimiento', 'hei_heist_kit_bin_01', 150},
        {'Aparador', 'hei_heist_str_sideboardl_03', 150, true},
        {'Carrito', 'hei_prop_hei_cash_trolly_03', 150},
        {'Bolsa', 'hei_prop_hei_paper_bag', 150},
        {'Contador', 'p_new_j_counter_02', 150},
        {'Fruta 1', 'apa_mp_h_acc_fruitbowl_01', 150},
        {'Fruta 2', 'apa_mp_h_acc_fruitbowl_02', 150},
        {'Fruta 3', 'prop_bar_fruit', 150},
        {'Fruta 4', 'prop_bar_lemons', 150},
        {'Fruta 5', 'prop_bar_measrjug', 150},
        {'Sink', 'prop_bar_sink_01', 150},
        {'Cuchilla de carnicero', 'prop_cleaver', 150},
        {'Taburete de cocina', 'v_ilev_fh_kitchenstool', 150},
        {'Refrigerador 1', 'prop_trailr_fridge', 150},
        {'Refrigerador 2', 'prop_fridge_01', 150},
        {'Refrigerador 3', 'prop_fridge_03', 150},
        {'Vend 1', 'prop_vend_fridge01', 150},
        {'Vend 2', 'prop_vend_snak_01', 150},
        {'Vend 3', 'prop_vend_coffe_01', 150},
        {'Vend 4', 'prop_vend_soda_01', 150},
        {'Vend 5', 'prop_vend_soda_02', 150},
        {'Vend 6', 'prop_vend_water_01', 150},
        {'Vend 7', 'prop_watercooler', 150}
    },
    ['bathroom'] = {
        {'Toalla', 'prop_shower_towel', 150},
        {'Toalla 2', 'p_shower_towel_s', 150},
        {'Toalla 3', 'v_res_mbtowel', 150},
        {'Toalla 4', 'v_res_mbtowelfld', 150},
        {'Rejilla de ducha', 'prop_shower_rack_01', 150},
        {'Baño', 'v_res_mbath', 150},
        {'Bañera', 'apa_mp_h_bathtub_01', 150},
        {'Contador', 'p_new_j_counter_02', 150},
        {'Loción 1', 'prop_beach_lotion_01', 150},
        {'Loción 2', 'prop_beach_lotion_02', 150},
        {'Loción 3', 'prop_beach_lotion_03', 150},
        {'Tijeras', 'prop_clippers_01', 150},
        {'Inodoro 1', 'prop_toilet_01', 150},
        {'Inodoro 2', 'prop_ld_toilet_01', 150},
        {'Jabón', 'prop_soap_disp_01', 150},
        {'Sink 1', 'prop_sink_02', 150},
        {'Sink 2', 'prop_sink_03', 150},
        {'Sink 3', 'prop_sink_04', 150},
        {'Sink 4', 'prop_sink_05', 150},
        {'Sink 5', 'prop_sink_06', 150},
        {'Sink 6', 'v_res_mbsink', 150},
        {'Handdry', 'prop_handdry_01', 150},
        {'Handdry 2', 'prop_handdry_02', 150}
    },
    ['Bins'] = {
        {'Compartimiento 1', 'prop_cs_bin_02', 100}, 
        {'Compartimiento 2', 'prop_cs_bin_03', 100}, 
        {'Compartimiento 3', 'prop_fbibombbin', 100}, 
        {'Compartimiento 4', 'prop_rub_binbag_sd_01', 100},
        {'Compartimiento 5', 'prop_rub_binbag_sd_01', 100},
        {'Compartimiento 6', 'prop_bin_04a', 150},
        {'Compartimiento 7', 'prop_bin_07a', 150},
        {'Compartimiento 8', 'prop_bin_06a', 150},
        {'Compartimiento 9', 'prop_bin_10b', 150},
        {'Compartimiento 10', 'prop_bin_11b', 150},
        {'Compartimiento 11', 'prop_bin_11a', 150},
        {'Compartimiento Largo', 'prop_bin_13a', 150},
        {'Bolsa de basura', 'prop_rub_binbag_sd_01', 100}
    },
    ['Storage'] = {
        {'Armario', 'p_cs_locker_01_s', 300, true}, 
        {'Armario 2', 'p_cs_locker_02', 300, true}, 
        {'Armario 3', 'p_cs_locker_01', 300, true}, 
        {'Caja Lester', 'prop_cs_lester_crate', 150},
        {'Champ Box', 'prop_champ_box_01', 225},
        {'Caja 1', 'prop_lev_crate_01', 225, true},
        {'Gabinete 1', 'prop_cabinet_02b', 225, true},
        {'Gabinete 2', 'prop_cabinet_01b', 225, true},
        {'Caja Devin', 'prop_devin_box_closed', 225, true},
        {'Caja 2', 'prop_mil_crate_01', 225, true},
        {'Caja 3', 'prop_mil_crate_02', 225, true},
        {'Caja fuerte 1', 'prop_ld_int_safe_01', 225, true},
        {'Caja fuerte 2', 'p_v_43_safe_s', 225, true},
        {'Caja fuerte 3', 'prop_ld_int_safe_01', 225, true},
        {'Mesa de madera', 'prop_mil_crate_02', 225, true},
        {'Gabinete', 'prop_fbibombfile', 225, true},
        {'Caja de armas', 'p_secret_weapon_02', 225, true},
        {'Caja de arma', 'prop_gun_case_02', 225, true},
        {'Ataúd', 'prop_coffin_02b', 225, true}
    },
    ['accessory'] = {
        {'Reloj', 'p_watch_02_s', 75},
        {'Reloj 2', 'p_watch_01_s', 75},
        {'Paquete de cigarrillos', 'p_cigar_pack_02_s', 75},
        {'Paquete de cigarrillos 2', 'p_fag_packet_01_s', 75},
        {'Billetera', 'prop_ld_wallet_01_s', 75},
        {'Bolso', 'prop_ld_handbag_s', 75},
        {'Bolsa', 'prop_m_pack_int_01', 75},
        {'Bolsa 2', 'prop_cs_heist_bag_02', 75},
        {'Bolso Nigel', 'prop_nigel_bag_pickup', 75},
        {'Maleta', 'prop_ld_suitcase_01', 75},
        {'Poste de stripper', 'prop_strip_pole_01', 75},
        {'Silla (lap dance)', 'apa_mp_h_stn_chairarm_01', 75},
    },
}