Strings = {
    -- blips
    ["purchasable_house"] = "Casa comprable",
    ["owned_house"] = "Casa en propiedad",
    ["access_house"] = "Casa Compartida",
    ["purchased_house"] = "Casa de alguien",

    ["purchasable_apartment"] = "Apartamento adquirible",
    ["owned_apartment"] = "Apartamento en propiedad",
    ["access_apartment"] = "Apartmento compartido",
    ["purchased_apartment"] = "Apartamento de alguien",

    ["ikea"] = "IKEA",
    ["robbery"] = "Casa robable",

    -- text for buttons
    ["buy_house"] = "Presiona ~INPUT_CONTEXT~ para comprar %s (#%s) por $%s.",
    ["contact_rea"] = "Presiona ~INPUT_CONTEXT~ para ver %s [#%s]",
    ["contact_rea_nopreview"] = "Póngase en contacto con un agente de bienes raíces para comprar esta propiedad.",
    ["enter"] = "Presiona ~INPUT_CONTEXT~ para entrar al edificio.",
    ["door"] = "Presiona ~INPUT_CONTEXT~ para abrir el menú de la puerta (%s)",
    ["enter_ikea"] = "Presiona ~INPUT_CONTEXT~ para entrar al IKEA.\nPresiona   ~INPUT_DETONATE~ Para vender tu mueble.",
    ["furnishing"] = "Item: %s\nVelocidad: %s ~INPUT_COVER~ ~INPUT_TALK~\nUsa ~INPUT_WEAPON_WHEEL_PREV~ ~INPUT_WEAPON_WHEEL_NEXT~ Para mover el mueble arriba/abajo\nUsa ~INPUT_ATTACK~ ~INPUT_AIM~ para rotar el mueble\nUsa ~INPUT_CELLPHONE_LEFT~ ~INPUT_CELLPHONE_RIGHT~ ~INPUT_CELLPHONE_UP~ ~INPUT_CELLPHONE_DOWN~ para mover el mueble\nPresiona ~INPUT_DETONATE~ para teletransportar el mueble hacia vos\nPresiona ~INPUT_FRONTEND_RDOWN~ para confirmar.\nPresiona ~INPUT_FRONTEND_RRIGHT~ para cancelar.",
    ["access_storage"] = "Presiona ~INPUT_DETONATE~ para acceder al almacenamiento.",
    ["press_manage"] = "\nPresiona ~INPUT_DETONATE~ para administrar esta casa",
    ["enter_garage"] = "Presiona ~INPUT_CONTEXT~ para entrar al garaje.",
    ["store_garage"] = "Presiona ~INPUT_CONTEXT~ para almacenar el vehículo.",
    ["breach_door"] = "\nPresiona ~INPUT_DETONATE~ para romper la puerta.",
    ["lockpick_door"] = "\nPresiona ~INPUT_DETONATE~ para ganzuar la puerta.",
    ["pole_dance"] = "Presiona ~INPUT_CONTEXT~ a pole baile",
    ["stop_dancing"] = "Presiona ~INPUT_VEH_DUCK~ dejar de bailar",
    ["lap_dance"] = "Presiona ~INPUT_CONTEXT~ bailar en el regazo\nPresiona   ~INPUT_VEH_EXIT~ sentarse",
    ["storage_wardrobe"] = "Almacenamiento o armario",
    ["storage_option"] = "Almacenamiento abierto",
    ["wardrobe_option"] = "Armario abierto",
    ["select_outfit"] = "Elige un atuendo",
    ["lockpicking"] = "Cuando la cerradura se ralentiza, estás cerca de la posición correcta..\nLlaves maestras restantes: %s\n\nUsa ~INPUT_CELLPHONE_LEFT~ ~INPUT_CELLPHONE_RIGHT~ para girar la cerradura\n~INPUT_FRONTEND_RDOWN~ desbloquear\n~INPUT_FRONTEND_RRIGHT~ Cancelar",

    -- ikea
    ["viewing_furniture"] = "Buscando %s.\nUsa ~INPUT_REPLAY_BACK~ ~INPUT_REPLAY_ADVANCE~ para cambiar el artículo.\nUsa ~INPUT_REPLAY_FFWD~ ~INPUT_REPLAY_REWIND~ para cambiar de categoría.\nUsa ~INPUT_MOVE_LEFT_ONLY~ ~INPUT_MOVE_RIGHT_ONLY~ para rotar el objeto.\nUsa ~INPUT_MOVE_UP_ONLY~ ~INPUT_MOVE_DOWN_ONLY~ hacer zoom.%s\nPresiona ~INPUT_FRONTEND_RDOWN~ comprar ~b~%s~s~ por ~g~$%s~s~.\nPresiona ~INPUT_FRONTEND_RRIGHT~ para salir de IKEA.",
    ["confirm_purchase"] = "Comprar %s por $%s?\n\n~INPUT_FRONTEND_RDOWN~ Comprar\n~INPUT_FRONTEND_RRIGHT~ Cancelar",
    ["purchased"] = "Comprado %s por $%s.",
    ["storage"] = "\nPuedes almacenar cosas en este artículo..",

    -- locked state
    ["locked"] = "Bloqueado",
    ["unlocked"] = "Desbloqueado",
    
    -- text for menus 
    ["house_key"] = "llave de casa",
    ["door_menu"] = "Menú de puerta",
    ["toggle_lock"] = "Bloqueo / desbloqueo",
    ["exit"] = "Salir",
    ["furnish"] = "Amueblar",
    ["put_furniture"] = "Colocar muebles",
    ["manage_furniture"] = "Gestionar muebles",
    ["amount_furniture"] = "x%s %s",
    ["confirm_house_purchase"] = "Comprar %s por <span style='color:lime'>$%s</span>",
    ["are_you_sure"] = "Comprar %s?",
    ["what_interior"] = "Que interior quieres?",
    ["interior_number"] = "Interior #%s",
    ["remove_furniture"] = "Eliminar %s?",
    ["inventory"] = "Almacenamiento",
    ["inventory_weapons"] = "Almacenamiento - armas",
    ["inventory_items"] = "Almacenamiento - objetos",
    ["black_money"] = "Dinero negro: <span style='color:red'>$%s</span>",
    ["cash"] = "Dinero: <span style='color:lime'>$%s</span>",
    ["put"] = "Depósitar objeto",
    ["get"] = "Retirar objeto",
    ["deposit"] = "Depositar",
    ["withdraw"] = "Retirar",
    ["weapons"] = "Armas",
    ["items"] = "Objetos",
    ["amount_of"] = "Cantidad de %s?",
    ["make_key_copy"] = "Haga una copia de su Llave",
    ["resell_house"] = "Vender la casa por <span style='color:lime'>$%s</span>",
    ["kick_someone_out"] = "Echar a alguien",
    ["kick_out?"] = "Echar a patadas %s?",
    ["kick_out"] = "Echaste a %s",
    ["preview"] = "Vista previa de posibles interiores",
    ["previewing"] = "Vista previa de interiores\n\nVista previa del interior %s de %s posibles.\nUsa ~INPUT_CELLPHONE_LEFT~ ~INPUT_CELLPHONE_RIGHT~ para ver otro interior\nPresiona ~INPUT_FRONTEND_RRIGHT~ para dejar de ver.",
    ["previewing_nohelp"] = "Vista previa de la casa\nPóngase en contacto con un agente inmobiliario para comprar esta casa.\nPresiona ~INPUT_FRONTEND_RRIGHT~ para dejar de ver.",
    ["transfer_house"] = "Transferir propiedad",
    ["transfer_property"] = "Transferir propiedad a %s?",
    ["none_nearby"] = "No hay nadie cerca",
    ["yes"] = "Si",
    ["no"] = "No",
    ["no_outfits"] = "No tienes ningún atuendo guardado.",
    ["confirm_delete"] = "Eliminar atuendo \"%s\"?",
    ["equip_outfit"] = "Equipar atuendo",
    ["delete_outfit"] = "Eliminar atuendo",

    -- text for notifications
    ["no_spawn"] = "No se pudo encontrar una ubicación para la casa/apartamento.\n\nDígale al propietario de su servidor que agregue más ubicaciones.",
    ["error_locked"] = "No se pudo entrar a la casa/apartamento - la puerta está cerrada.",
    ["not_near_door"] = "No está cerca de la puerta y, por lo tanto, no puede bloquearla/desbloquearla..",
    ["must_be_number"] = "Debes ingresar un número.",
    ["dont_have"] = "No tienes tanto.",
    ["not_enough"] = "No hay suficiente en el almacenamiento.",
    ["cant_carry"] = "No puedes cargar tanto.", 
    ["has_items"] = "Este objeto tiene elementos y, por lo tanto, no puede eliminarlo. ¡Asegúrate de vaciar el almacenamiento!",
    ["someone_in_house_cant_sell"] = "Alguien está en la casa, ¡no puedes venderlo ahora!",
    ["cant_own_more"] = "No puedes tener más propiedades.",
    ["no_lockpicks"] = "No tienes una Llave Maestra.",
    ["robbery_progress"] = "ALERTA!! ¡Alguien está robando una casa! ¡Comprueba tu GPS!",
    ["you_got_kicked"] = "Te echaron de la casa.",
    ["house_spawned_transfer"] = "Alguien está adentro, no se puede transferir la propiedad.",
    ["nolonger_nearby"] = "El jugador ya no está cerca.",
    ["nearby_storage"] = "Alguien está cerca y, por lo tanto, no puede acceder al almacenamiento..",
    ["locked_door"] = "Cerraste la puerta",
    ["unlocked_door"] = "Abriste la puerta",

    -- text for loading
    ["purchasing"] = "Comprando",
    ["removing_furniture"] = "Removiendo Mueble",
    ["loading_object"] = "Cargando objeto",
    ["loading_storage"] = "Cargando almacenamiento",

    -- other
    ["rotation"] = "Rotacion: %s",
    ["not_enough_cops"] = "¡No hay suficientes policías en línea!",
}